services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: canok
      POSTGRES_PASSWORD: pass-123
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

