
spring:
  datasource:
    main: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    password: pass-123
    pool-size: 10
    username: canok
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
